### PR TITLE
[WIP] Ansible Controller

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Adds an Ansible resource controller for managing Kubernetes resources using [Ansible Playbook Bundles](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle) and a Custom Resource Definition.

**New CLI flags:**
- `apb-dir`: Absolute path to the APB directory

### Implementation

**ResourceAdded:** Roughly maps to the `provision` playbook.

**ResourceUpdated:** Roughly maps to the `update` playbook.

**ResourceDeleted:** Roughly maps to the `deprovision` playbook.

### Open Questions

- [x] What do we vendor to make this work (`apb`/`oc`)?
  - `ansible-playbook` is used by the `apb-base` image to [execute the playbooks](https://github.com/ansibleplaybookbundle/apb-base/blob/master/files/usr/bin/entrypoint.sh#L56), so we can install Ansible into the Lostromos container and "shell out" \*_shudder_\*
- [x] How do we "[bind](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md#bind---execute-from-the-user-interface)" template values using CRs?
  - pass JSON object to the `--extra-vars` flag of `ansible-playbook` command
- [x] Does `apb` support updating resources after they are provisioned?
  - [Service Broker API has an update method](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openservicebrokerapi/servicebroker/master/openapi.yaml#/ServiceInstances/serviceInstance.update)
- [x] Do we need another repo for `apb-app-operator-kit`?
  - yes
- [x] Is it enought to provide just APB container image or do we need the full directory containing the [APB files](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md#using-apb-init)?
  - If we "shell out" to `ansible-playbook`, then we need the whole APB directory
  - Can mount APB directory [using ConfigMaps](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/developers.md#using-a-configmap-within-an-apb)
  - need to inherit APB container for environment dependencies (`psql`, `oc`, `kubectl`, etc)
- [ ] Can we add `ownerReferences` to the k8s resources created by Ansible?

### CODE REVIEW

**Comment by ecordell** [comment]
> What do we vendor to make this work (apb)?

From a quick skim it looks like this is the meat of "driving" an APB:

https://github.com/openshift/ansible-service-broker/blob/master/pkg/apb/executor.go#L141

This assumes we're deploying APBs, which as far as I can tell are ansible playbooks bundled up into a docker container that you call with different args to trigger the different actions. 

We could do that exact thing here, but since we're already building a docker container we should probably cut out the middleman - load the ansible bundle directly into the container, and execute the provision/deprovision scripts it provides.

This goes over the APB architecture: https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/design.md

I think lostromos is really replacing the APB in this case - instead of a short lived container that performs an ansible action, we want a long-running container that performs ansible actions in response to CRs. 

APBs do this by calling `ansible-playbook`: https://github.com/ansibleplaybookbundle/apb-base/blob/master/files/usr/bin/entrypoint.sh#L56

https://docs.ansible.com/ansible/2.4/ansible-playbook.html

So it looks like we just need to load a playbook into a container with ansible-playbook installed and shell out. 

> Does apb support updating resources after they are provisioned?

OSB API has an `update` command but it doesn't look like there's anything to support that in APBs as far as I can tell.

We might be able to get away with using the `spec` field of the CR as "extra vars":

https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/c4b7debdee8cd9cdbd42cec1fde66c3a80e2a28c/docs/developers.md#kubernetes-and-openshift

> Do we need another repo for apb-app-operator-kit?

Yes, at least for now.

**Comment by jwmatthews** [comment]
Keep in mind that playbooks/roles may have 3rd party requirements, one of the benefits with the APB approach is you know all of the dependencies are handled for you in the image, especially when dealing with manipulating off-cluster resources external libraries/modules grow more prevalent.  

For an initial spike, keeping things simple to work with a playbook has value, as requirements evolve we likely will want the ability to execute arbitrarily complex Ansible with all of the dependent roles/modules/libraries bundled together.

As to APB update we have a few examples that use update for doing things such as updating parameters, switching OSB plans,  to performing an upgrade/downgrade of versions.

Postgres APB is a good example of an APB using update:
 https://github.com/ansibleplaybookbundle/postgresql-apb/blob/master/playbooks/update.yaml

**Comment by alecmerdler** [comment]
@jwmatthews The goal here is to have a k8s custom resource (i.e. `postgresdbs.apb.redhat.com`) that maps 1:1 with an APB. This is the basic building block for managing apps using ALM. 

The value of adding functionality to Lostromos to simply execute `kubectl run --image=<apb>` seems like an extra, unnecessary layer. It sounds like your work to expose CRDs for the Ansible Broker is a much cleaner solution.

**Comment by alecmerdler** [comment]
Per discussion w/ @ecordell, our approach will be:
1. Use APB as base image (to get all the playbook dependencies)
2. Add Lostromos binary
3. Lostromos watches CRs and executes `ansible-playbook <apb-image> <playbook>.yml  --extra-args=<args-from-cr>`
4. Resulting container runs as `example-apb-operator` in the cluster

**Comment by alecmerdler** [comment]
@jwmatthews @ecordell @jzelinskie  Did you have any more ideas/suggestions for what to try out in this spike branch?

**Pull request closed without merging**
